spring:
  profiles:
    active: dev
  cloud:
    config:
      override-none: true
      override-system-properties: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
