spring:
  profiles:
    active: dev
  cloud:
    config:
      override-none: true
      override-system-properties: false
    discovery:
      enabled: true
    gateway:
      routes:
        - id: main_module
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/main/**
          filters:
            - StripPrefix=3
        - id: stream_module
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stream/**
          filters:
            - StripPrefix=3

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
