server:
  port: 8080
  
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: main_module
          uri: lb://MAIN
          predicates:
            - Path=/api/v1/main/**
        - id: stream_module
          uri: lb://STREAM
          predicates:
            - Path=/api/v1/stream/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka
