server:
  port: 8080
  
spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: main_module
          uri: lb://MAIN:8081
          predicates:
            - Path=/api/v1/main/**
        - id: stream_module
          uri: lb://STREAM:8082
          predicates:
            - Path=/api/v1/stream/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
