spring:
  cloud:
    config:
      override-none: true
      override-system-properties: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  level:
    '[ROOT]': DEBUG
